# Generated by Django 5.1.4 on 2025-05-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_expense_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(verbose_name='Yaratilgan vaqti'),
        ),
    ]
