# Generated by Django 5.1.4 on 2025-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(null=True, verbose_name='Yaratilgan vaqti'),
        ),
    ]
