# Generated by Django 5.1.4 on 2025-06-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_botuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='username',
        ),
    ]
