# Generated by Django 5.1.4 on 2025-06-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_botuser_is_active_remove_botuser_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='botuser',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='language',
            field=models.CharField(choices=[('uz_latin', "O'zbekcha (Lotin)"), ('uz_cyrillic', 'Ўзбекча (Кирил)'), ('russian', 'Русский')], default='uz_latin', max_length=20),
        ),
    ]
