# Generated by Django 5.1.4 on 2025-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_created_at_botuser_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True, verbose_name='Bino shifri'),
        ),
        migrations.AddField(
            model_name='building',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Bino joylashuvi'),
        ),
    ]
