# Generated by Django 5.1.4 on 2025-07-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_building_code_building_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Operator ismi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operatorlar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LeadStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bosqich nomi')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Kalit (inglizcha)')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Rang (HEX)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_system_stage', models.BooleanField(default=False, verbose_name='Tizim bosqichi')),
            ],
            options={
                'verbose_name': 'Lead Bosqichi',
                'verbose_name_plural': 'Lead Bosqichlari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mijoz ismi')),
                ('call_status', models.CharField(blank=True, choices=[('answered', 'Javob berildi'), ('not_answered', 'Javob berilmadi'), ('client_answered', 'Mijoz javob berdi'), ('client_not_answered', 'Mijoz javob bermadi')], max_length=20, null=True, verbose_name="Qo'ng'iroq holati")),
                ('call_duration', models.DurationField(blank=True, null=True, verbose_name="Qo'ng'iroq davomiyligi")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('audio_recording', models.FileField(blank=True, null=True, upload_to='lead_audio/', verbose_name='Audio yozuv')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='Keyingi aloqa sanasi')),
                ('is_converted', models.BooleanField(default=False, verbose_name='Mijozga aylangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clientinformation', verbose_name='Aylantirilgan mijoz')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.calloperator', verbose_name='Operator')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.leadstage', verbose_name='Bosqich')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leadlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
