# Generated by Django 5.1.4 on 2025-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_calloperator_leadstage_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='olchami',
            field=models.IntegerField(blank=True, null=True, verbose_name="O'lchami"),
        ),
    ]
