# Generated by Django 5.1.4 on 2025-12-04 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_building_olchami'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.PositiveIntegerField(unique=True, verbose_name='Shartnoma raqami')),
                ('contract_date', models.DateField(default=django.utils.timezone.now, verbose_name='Shartnoma sanasi')),
                ('contract_location', models.CharField(default='Xiva', max_length=150, verbose_name='Shartnoma tuzilgan joy')),
                ('client_full_name', models.CharField(max_length=255, verbose_name='Buyurtmachi ism familiyasi')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Passport raqami')),
                ('passport_issue_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport berilgan sana')),
                ('passport_issue_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Passport bergan tashkilot')),
                ('client_address', models.CharField(max_length=255, verbose_name='Buyurtmachining manzili')),
                ('phone_primary', models.CharField(max_length=20, verbose_name='Telefon raqam 1')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam 2')),
                ('service_name', models.CharField(max_length=255, verbose_name='Xizmat nomi')),
                ('service_country', models.CharField(default='Angliya', max_length=150, verbose_name='Xizmat davlati')),
                ('visa_type', models.CharField(max_length=150, verbose_name="Visa turi yoki yo'nalish")),
                ('service_description', models.TextField(blank=True, verbose_name='Xizmat tavsifi')),
                ('total_service_fee', models.PositiveIntegerField(verbose_name="Umumiy xizmat summasi (so'm)")),
                ('initial_payment_amount', models.PositiveIntegerField(default=0, verbose_name="Boshlang'ich to'lov")),
                ('initial_payment_due_days', models.PositiveIntegerField(default=3, verbose_name="Boshlang'ich to'lov muddati (kun)")),
                ('post_interview_payment_amount', models.PositiveIntegerField(default=0, verbose_name="Suhbatdan keyingi to'lov")),
                ('post_interview_due_days', models.PositiveIntegerField(default=3, verbose_name="Suhbatdan keyingi to'lov muddati (kun)")),
                ('refund_amount', models.PositiveIntegerField(default=0, verbose_name="Qaytariladigan summa (agar kerak bo'lsa)")),
                ('service_duration_months', models.PositiveIntegerField(default=8, verbose_name='Xizmat davri (oy)')),
                ('amount_paid', models.PositiveIntegerField(default=0, verbose_name="Haqiqiy to'langan summa")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('preparation', 'Hujjat tayyorlanmoqda'), ('submitted', 'Taqdim etildi'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='preparation', max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha izohlar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konsalting shartnomasi',
                'verbose_name_plural': 'Konsalting shartnomalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
