# Generated by Django 5.1.4 on 2025-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_consultingcontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingcontract',
            name='service_description',
            field=models.TextField(blank=True, null=True, verbose_name='Xizmat tavsifi'),
        ),
    ]
