# Generated by Django 5.1.4 on 2025-12-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_consultingcontract_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yashash manzili'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='passport_issue_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport berilgan sana'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='passport_issue_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Passport bergan tashkilot'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport raqami'),
        ),
        migrations.AddField(
            model_name='consultingcontract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consulting_contracts', to='main.clientinformation', verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='consultingcontract',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Buyurtmachining manzili'),
        ),
        migrations.AlterField(
            model_name='consultingcontract',
            name='client_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Buyurtmachi ism familiyasi'),
        ),
        migrations.AlterField(
            model_name='consultingcontract',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Passport raqami'),
        ),
        migrations.AlterField(
            model_name='consultingcontract',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqam 1'),
        ),
        migrations.CreateModel(
            name='ContractFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism familiya")),
                ('relationship', models.CharField(choices=[('father', 'Ota'), ('mother', 'Ona'), ('son', "O'g'il"), ('daughter', 'Qiz'), ('spouse', "Turmush o'rtog'i"), ('brother', 'Aka/uka'), ('sister', 'Opa/singil'), ('other', 'Boshqa')], max_length=20, verbose_name='Qarindoshlik darajasi')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Passport raqami')),
                ('passport_issue_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport berilgan sana')),
                ('passport_issue_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Passport bergan tashkilot')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumotlar")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='main.consultingcontract', verbose_name='Shartnoma')),
            ],
            options={
                'verbose_name': 'Shartnoma qarindoshi',
                'verbose_name_plural': 'Shartnoma qarindoshlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
