# Generated by Django 5.1.4 on 2025-12-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_clientinformation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Ism'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Familiya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharif'),
        ),
        migrations.AddField(
            model_name='consultingcontract',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ism'),
        ),
        migrations.AddField(
            model_name='consultingcontract',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Familiya'),
        ),
        migrations.AddField(
            model_name='consultingcontract',
            name='client_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharif'),
        ),
        migrations.AddField(
            model_name='contractfamilymember',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Ism'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractfamilymember',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Familiya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractfamilymember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sharif'),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='contractfamilymember',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name="To'liq ism familiya"),
        ),
    ]
