# Generated by Django 5.1.4 on 2025-12-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_clientinformation_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Elektron pochta'),
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='password',
            field=models.CharField(blank=True, help_text='Mijoz uchun parol', max_length=255, null=True, verbose_name='Parol'),
        ),
        migrations.AddField(
            model_name='consultingcontract',
            name='completed_contract_images',
            field=models.JSONField(blank=True, default=list, help_text='Maksimal 3 ta rasm', verbose_name='Yakunlangan shartnoma rasmlari'),
        ),
        migrations.AddField(
            model_name='consultingcontract',
            name='passport_images',
            field=models.JSONField(blank=True, default=list, help_text='Maksimal 2 ta rasm', verbose_name='Passport/ID karta rasmlari'),
        ),
    ]
