# Generated by Django 5.1.4 on 2025-12-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_clientinformation_email_clientinformation_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='heard',
            field=models.CharField(default='Xech qayerda', max_length=200, verbose_name='Qayerda eshitgan'),
        ),
    ]
