# Generated by Django 5.1.4 on 2025-12-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_consultingcontract_passport_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultingcontract',
            name='passport_expiry_date',
        ),
        migrations.RemoveField(
            model_name='contractfamilymember',
            name='passport_expiry_date',
        ),
        migrations.AddField(
            model_name='clientinformation',
            name='passport_expiry_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='consultingcontract',
            name='passport_images',
            field=models.JSONField(blank=True, default=list, help_text='Maksimal 1 ta rasm', verbose_name='Zagran passport rasmlari'),
        ),
        migrations.AlterField(
            model_name='consultingcontract',
            name='visa_images',
            field=models.JSONField(blank=True, default=list, help_text='Maksimal 1 ta rasm', verbose_name='VISA rasmlari'),
        ),
    ]
