# Generated by Django 5.1.4 on 2025-12-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_readd_passport_expiry_contract_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
    ]
