# Generated by Django 5.1.4 on 2025-12-15 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_change_birth_date_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultingcontract',
            name='contract_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Shartnoma sanasi'),
        ),
    ]
